name = "SparseMatricesCSR"
uuid = "a0a7dd2c-ebf4-11e9-1f05-cf50bc540ca1"
authors = ["VÃ­ctor Sande <vsande@cimne.upc.edu>", "Francesc Verdugo <fverdugo@cimne.upc.edu>"]
version = "0.6.10"

[deps]
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[compat]
Atomix = "1.1.2"
Polyester = "0.7.19"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
